server:
  port: 4567

spring:
  application:
    name: api-gateway
#  cloud:
#    gateway:
#      routes:
#        - id: Security-service
#          uri: http://localhost:9004
#          predicates: 
#                - Path=/**
#                
#        - id: LOCATION-SERVICE
#          uri: http://localhost:9003
#          predicates:
#          - Path=/location/**         





eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
      
cloud:
  gateway:
    routes:
      - id: employee-service-route
        uri: lb://employee-service
        predicates:
          - Path=/employee/**
          
      - id: department-service-route
        uri: lb://department-service
        predicates:
          - Path=/department/**
          
      - id: location-service-route
        uri: lb://location-service
        predicates:
          - Path=/location/**

                