server:
  port: 4567

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: Security-service
          uri: http://localhost:9004
          predicates:
            - Path=/**
